services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: michelin_guide_database

    volumes:
      - /home/socrates/ghq/github.com/roycehoe/michelin-guide/data:/data/db
    ports:
      - 27017:27017
    depends_on:
      - app

  app:
    build: .
    ports:
      - 8000:8000


  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/